apps/partners/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from .views import register


urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='static/partner.html'), name='index'),
    url(r'^register/$', register, name='register'),
    url(r'^thank-you/$', TemplateView.as_view(template_name='partners/thankyou.html'), name='thanks')
)

indiandelights/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from apps.product import urls as app_product_urls
from apps.product import views as app_product_view
from apps.home import views as app_home_view
from apps.partners import urls as app_partners_urls


urlpatterns = patterns('',
    url(r'^$', app_home_view.home_page, name='home_page'),
    url(r'^vendors/$', app_home_view.vendor_view, name='vendor_view'),
    url(r'^cart/$', app_product_view.cart_view, name='cart_view'),
    url(r'', include(app_product_urls)),
    url(r'partners/', include(app_partners_urls, namespace='partners')),
    url(r'^site/terms/$', TemplateView.as_view(template_name='static/terms.html'), name='site_terms'),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/_includes/main_footer.html
<div id="main__bottom__footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <ul class="list-unstyled">
          <li><span class="font__bold">Help</span></li>
          <li><a href="#">Payment</a></li>
          <li><a href="#">Shipping</a></li>
          <li><a href="#">Cancellation</a></li>
          <li><a href="#">Faqs</a></li>
        </ul>
      </div>
      <div class="col-md-3">
        <ul class="list-unstyled">
          <li><span class="font__bold">Legal</span></li>
        </ul>
      </div>
    </div>
  </div>
</div>

templates/_includes/sub_nav.html
{% load cart_tags %}
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h4><a class="no__style__link" href="#"><span style="color: #0085a1;" class="icon icon-shop"></span> <span style="color: #362c1b;" class="font__bold">Flavood</a></h4>
    </div>
    <div class="col-sm-3 col-sm-offset-2">
      <div class="input-group">
          <input type="text" class="form-control" placeholder="Search">
          <span class="input-group-btn">
              <button class="btn btn-default btn__stylish--default" type="button">Go!</button>
          </span>
      </div>
    </div>
    <div class="col-sm-3">
        {% get_cart as main_cart %}
        <div class="dropdown">
          <button class="btn btn-default btn__stylish--default dropdown-toggle" type="button" id="main__cart__dropdown__menu" data-toggle="dropdown">
            <span class="icon icon-shopping-cart"></span> Cart <sup><span id="cart__default__count" class="label label-default">{{ main_cart.count }}</span></sup>
            <span class="caret"></span>
          </button>
          <div id="cart__dropdown_parent" class="dropdown-menu" role="menu" aria-labelledby="main__cart__dropdown__menu">
            <div id="cart__dropdown">
              {% if main_cart.count == 0 %}
                <p class="text-info">Your cart is empty</p>
              {% else %}
                {% for k, v in main_cart.cart_dict.items %}
                  <div class="media">
                    <a href="#" class="pull-left"><img width="40" height="36" src="{{ v.thumbnail }}" alt=""></a>
                    <div class="media-body">
                      <a href="#">{{ v.name }}</a>
                      <p>Qty - {{ v.qty }} X {{ v.qty_display }}</p>
                    </div>
                  </div>
                {% endfor %}
              {% endif %}
            </div>
            <div class="{% if main_cart.count == 0 %} hide {% endif %}" id="main__cart__btn__codes">
              <button class="btn btn-default">Checkout</button>&nbsp;&nbsp;&nbsp;<a href="{% url 'cart_view' %}" class="btn btn-success">View Cart</a>
            </div>
          </div>
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <ul class="nav nav-tabs nav__tabs--outer" role="tablist">
        <li {% if request.resolver_match.url_name == "home_page" %} class="active" {% endif %}><a href="{% url 'home_page' %}">Home</a></li>
        <li {% if request.resolver_match.url_name == "vendor_view" %} class="active" {% endif %} ><a href="{% url 'vendor_view' %}">All vendors</a></li>
      </ul>
    </div>
  </div>
</div>

templates/_includes/top_nav.html
<nav class="navbar navbar__top__in" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".bs-example-toolbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse bs-example-toolbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'home_page' %}">Home</a></li>
        <li><a href="#">Login</a></li>
        <li><a href="#">Contact</a></li>
        <li><a href="#">Track Order</a></li>
        <li><a href="{% url 'site_terms' %}">Terms</a></li>
        <li><a href="{% url 'partners:index' %}">Become a partner</a></li>
      </ul>
    </div>
  </div>
</nav>