apps/partners/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from .views import register


urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='static/partner.html'), name='index'),
    url(r'^register/$', register, name='register'),
    url(r'^thank-you/$', TemplateView.as_view(template_name='partners/thankyou.html'), name='thanks')
)

indiandelights/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from apps.product import urls as app_product_urls
from apps.product import views as app_product_view
from apps.home import views as app_home_view
from apps.partners import urls as app_partners_urls


urlpatterns = patterns('',
    url(r'^$', app_home_view.home_page, name='home_page'),
    url(r'^vendors/$', app_home_view.vendor_view, name='vendor_view'),
    url(r'^cart/$', app_product_view.cart_view, name='cart_view'),
    url(r'', include(app_product_urls)),
    url(r'partners/', include(app_partners_urls, namespace='partners')),
    url(r'^site/terms/$', TemplateView.as_view(template_name='static/terms.html'), name='site_terms'),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/partners/models.py
from django.db import models
from django.core.validators import RegexValidator


class Applicants(models.Model):

    email = models.EmailField('email adress', max_length=255, unique=True)
    name = models.CharField('Full name', max_length=100)
    phone = models.CharField('Phone number', max_length=12, validators=[
        RegexValidator(
            regex='((\+*)((0[ -]+)*|(91 )*)(\d{12}|\d{10}))|\d{5}([- ]*)\d{6}',
            message='Invalid phone number'
        )
    ], help_text='No need to write country code. In case of mobile just number and in case of landline stdcode and phone number. example 805012xxxx and for landline 03595 259506')
    business = models.CharField('Type of business', max_length=100)
    processed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

apps/partners/forms.py
from django.forms import ModelForm, widgets
from .models import Applicants


class ApplicantsForm(ModelForm):

    class Meta:
        model = Applicants
        fields = ['email', 'name', 'phone', 'business']
        widgets = {
            'email': widgets.EmailInput(
                attrs={
                    'placeholder': 'Email adress',
                    'required': 'true'
                },
            ),
            'name': widgets.TextInput(
                attrs={
                    'placeholder': 'Full name',
                    'required': 'true'
                },
            ),
            'phone': widgets.TextInput(
                attrs={
                    'placeholder': 'Contact number',
                    'required': 'true'
                },
            ),
            'business': widgets.TextInput(
                attrs={
                    'placeholder': 'Type of business',
                    'required': 'true'
                },
            ),
        }

apps/partners/views.py
from django.shortcuts import render, redirect
from .forms import ApplicantsForm
import logging


logger = logging.getLogger(__name__)


def register(request):
    logger.debug('register vendor called')
    template_name = 'partners/register.html'

    if request.method == 'GET':
        form = ApplicantsForm()
    else:
        form = ApplicantsForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('partners:thanks')
    return render(request, template_name, {'form': form})

templates/partners/register.html
{% extends '_layouts/base.html' %}
{% load bootstrap %}

{% block sub_nav %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
            <div class="partner__form__block">
                <div class="form__description__block">
                    <h4 class="font__mid">Sell with us</h4>
                    <p class="partner__sell__desc">By creating an account, you agree to be nice and post high quality content. The Designer News community bans users very liberally, so behave yourself. </p>
                </div>
                <form action="{% url 'partners:register' %}" class="form-horizontal partner__register__form" method="POST">
                    {% csrf_token %}
                    {{ form|bootstrap_horizontal }}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="submit" class="btn btn__register" value="Submit" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        $('body').addClass('partner__register__form__pg')
    })
</script>
{% endblock %}

templates/partners/thankyou.html
{% extends '_layouts/base.html' %}

{% block sub_nav %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
            <div class="partner__form__block">
                <h4 class="font__mid">Thank You !!!</h4>
                <p class="partner__sell__desc">We will contact you in next 24 hours to proceed your request.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        $('body').addClass('partner__register__form__pg')
    })
</script>
{% endblock %}